### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by hristoast** [treymerkley/openmw-nif-cleaner#7]
Thanks for your work on this!  I'm the author of modding-openmw.com and I'd like to list this tool on my website, but I noticed there's no license for the project.

According to [Github docs,](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) no license by default means "proprietary".  If this is not your intention I'd like to request that you add a license to the repository.

If you aren't sure what to pick, there are resources out there to help (like [this one](https://choosealicense.com/)) you pick one that matches your intent.

Thanks again!

**Comment by jrivany** [comment]
Thanks for pointing this out!

I created a PR for this, but I don't feel right merging it on my own right away, since it's licensing related and I didn't create the repo originally, just the original gist that the processor is based on.
