### ISSUE TITLE
Every file is written to after the first file that needs changes is encountered

### ISSUE THREAD

**Issue by benjaminwinger** [treymerkley/openmw-nif-cleaner#8]
The issue is basically that the file_changed flag in processor.py is declared too early and its value persists for subsequent files.

I'd make a pull request, but I don't have the rights to do so (see #7).

**Comment by jrivany** [comment]
You'd think a 20 line script would be easy to write without silly bugs...

It's even present in the [original script](https://gist.github.com/jrivany/0665e26759fd677eb52e44b8f93cc07a)...

I'll retreat to my closet of shame.
